language: objective-c
osx_image: xcode8.1
env:
  global:
    - ENCRYPTION_LABEL: "52e2892d3482"
    - COMMIT_AUTHOR_EMAIL: "jordi.aguila@gmail.com"
before_install:
  - gem install slather --no-ri --no-rdoc
script:
  - xcodebuild clean test -project ./workshop_protocols.xcodeproj -scheme workshop_protocols -destination 'platform=iOS Simulator,name=iPhone 7' TEST_AFTER_BUILD=YES -configuration Debug -enableCodeCoverage=YES
  - slather
  - ./publish-gh-pages.sh
  
